version: '3.7'

networks:
  postgres:

services:

  postgres:
    image: postgres:14.0
    container_name: postgres
    networks: 
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:6
    container_name: pgadmin
    networks: 
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80
    volumes: 
      - ./pgadmin:/var/lib/pgadmin

  cloudbeaver:
    image: dbeaver/cloudbeaver:21.1.5
    container_name: cloudbeaver
    networks:
      - postgres
    ports: 
      - 8978:8978
    volumes: 
      - ./dbeaver/workspace:/opt/cloudbeaver/workspace
    # user: cbadmin
    # pass: password
    
  omnidb:
    image: omnidbteam/omnidb:3.0.3b
    container_name: omnidb
    networks: 
      - postgres
    ports:
      - 8000:8000
    volumes: 
      - ./omnidb_server:/home/omnidb/.omnidb/omnidb-server
    
    # docker exec -it omnidb python omnidb-server.py --createsuperuser=root pass
