version: '3.7'

networks:
  postgres:

services:

  postgres:
    image: postgres:15.4
    container_name: postgres
    networks: 
      - postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres-scripts:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:7.6
    container_name: pgadmin
    networks: 
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    ports:
      - 8080:80
    volumes: 
      - ./pgadmin:/var/lib/pgadmin

  omnidb:
    platform: linux/amd64 # for apple processors
    image: omnidbteam/omnidb:3.0.3b
    container_name: omnidb
    networks: 
      - postgres
    ports:
      - 8000:8000
    volumes: 
      - ./omnidb_server:/home/omnidb/.omnidb/omnidb-server
